### ISSUE TITLE
About Node Classification

### ISSUE THREAD

**Issue by Yfhu1103** [DaehanKim/vgae_pytorch#1]
Hello, Thanks for releasing your work! I have seen that you said you use GAE for node classification tasks but can not get good results, have you found why? And could you plz release the code for node classification?

**Comment by DaehanKim** [comment]
Hi, @Mrslock.
I didn't do further experiments on that. As Kipf mentioned on his repo issue board, I also suspect main causes are lack of regularization such as early stopping or negative sampling. I'm afraid I don't have the specific implementation but you can easily try those unsupervised node classification. I referred to the description of a paper, 'A graph autoencoder for attributed network embedding'. 

Best regard,
Daehan
