### ISSUE TITLE
more graphs train

### ISSUE THREAD

**Issue by secuy** [DaehanKim/vgae_pytorch#10]
Hello, now if I have many graphs, how can train these data? It seems that the code can just train on one graph data.

**Comment by DaehanKim** [comment]
Hi @secuy 
This implementation is based on GCN architecture, which only supports link prediction within a single graph.
I strongly recommend you to check out other inductive frameworks such as GraphSAGE, which can predict node representations from unseen graphs.

**Comment by secuy** [comment]
Okay, thanks for your answer and suggestion
