### ISSUE TITLE
a small problem

### ISSUE THREAD

**Issue by chenbofeng123** [DaehanKim/vgae_pytorch#2]
kl_divergence = 0.5/ A_pred.size(0) * (1 + 2*model.logstd - model.mean**2 - torch.exp(model.logstd)).sum(1).mean()
torch.exp(model.logstd)**2  ?

**Comment by DaehanKim** [comment]
Dear @chenbofeng123,
Thank you for your correction! I'll update it.

**Comment by yyou1996** [comment]
I think should be:
kl_divergence = 0.5/ A_pred.size(0) * (1 + model.logstd - model.mean**2 - torch.exp(model.logstd)).sum(1).mean() ?
Please see line 143 of https://github.com/AntixK/PyTorch-VAE/blob/master/models/vanilla_vae.py.
