### ISSUE TITLE
Can this be used for clustering the nodes?

### ISSUE THREAD

**Issue by atheeraa** [DaehanKim/vgae_pytorch#4]
Hello, thank you for your great work. 
I'm new to graph networks, and I would appreciate it if you'd explain to me if this model can be used for clustering i.e. community detection? if not, can you recommend ways to employ a GCN or a GAE for community detection?

**Comment by DaehanKim** [comment]
I haven't tried the community detection task using graph auto encoders, but I can see quite many related works only by searching "community detection using graph auto encoder" in google scholar. How about starting with the top-cited one?

**Comment by atheeraa** [comment]
Thank you !
