### ISSUE TITLE
what type is the data

### ISSUE THREAD

**Issue by hubblechang** [DaehanKim/vgae_pytorch#6]
Excuse me, I have a question about the format of data. The extensions of these data files are 'x','tx', 'allx','graph' which I haven't seen before. Further more, what I can see is shown in the following picture when I open them with Pycharm.
![3YL {3PQ05)GVOX9_BWA~%D](https://user-images.githubusercontent.com/60973725/148383631-d2a5aec9-e651-4f34-adc2-bb87054f876e.png)

**Comment by DaehanKim** [comment]
Hi. As you can see in `load_data` function, these data are binary, so cannot be visualized directly via text editor. Hopefully printing out values in python would help you understand the structure.

**Comment by hubblechang** [comment]
Thank you for your reply  : ）
