### ISSUE TITLE
Can the vgae model reconstruct graph structures with weights?

### ISSUE THREAD

**Issue by hrnne** [DaehanKim/vgae_pytorch#8]

**Comment by DaehanKim** [comment]
Hi @hrnne, Thanks for your interest! 
VGAE model basically predicts (the probability of) binary edge. but you can regard the probability of an edge as some kind of weights. Hopefully there would be specific methods dealing with your case in recent publications. so highly recommend searching in Google Scholar.

**Comment by hrnne** [comment]
> Hi @hrnne, Thanks for your interest! VGAE model basically predicts (the probability of) binary edge. but you can regard the probability of an edge as some kind of weights. Hopefully there would be specific methods dealing with your case in recent publications. so highly recommend searching in Google Scholar.

I think reconstructing weights requires replacing a decoder. Do you have any suggestions? This is very important for my experiment, but I have been troubled for a long time. As you mentioned, the inner product decoder displays the connection probability between two nodes, so when reconstructing weights, if the predicted values are directly used as weights, vgae tends to assign a probability value to a large number of edges. Because my input is sparse, I actually expect to reconstruct many edges with weights of 0. Therefore, my experimental progress has been hindered. When conceptualizing the experiment, I didn't think it was very difficult to modify this model, but as the experiment progressed, I found that it was not simple and there was very little information about this model. Therefore, I sincerely hope you can provide me with some ideas.PLZ (╥_╥)
