### ISSUE TITLE
Run the model with other data

### ISSUE THREAD

**Issue by gaoshihao333** [DaehanKim/vgae_pytorch#9]
How do I turn other data into data that this code can use?

**Comment by DaehanKim** [comment]
Hi @qingninggo!
I'm afraid I don't provide additional preprocessing scripts so you need to build your own.
I recommend you to unpickle data binary files to inspect the structure.
You can put break point here(https://github.com/DaehanKim/vgae_pytorch/blob/master/input_data.py#L20)
to see how each data file is organised.

**Comment by gaoshihao333** [comment]
Thanks for replying, I have solved the problem, have a nice day!
